### ISSUE TITLE
About the library design and suggestions

### ISSUE THREAD

**Issue by AmraniCh** [peter279k/url-tracker#2]
### Problem

* The Guzzle client object is highly coupled to the `Trucker::trackFromUrl` method, we cannot mock HTTP calls and do unit tests properly.

### Suggestion

* Make the HTTP client object as a dependency of the `Trucker` class, so we can mock the object and alter the HTTP responses.
* Having an interface for HTTP clients that implements PSR-7, a library user may want to use other library for doing HTTP requests (for performance purposes for ex), we provide an interface with single method `Client::get($url)` that users must implements in order to pass it the Tracker object, this way our library is more flexible.

## Tracker class

* I suggest having the tracker class stateless, which means removing the `$url` property and let users work with only one instance to truck multiple URLs, like:

```php
// the HTTP client parameter is optional (Guzzle client will be used as the default HTTP client)
$tracker = new Tracker(new Lee\Http\Guzzle);
$tracker->track($url1);
$tracker->track($url2);
$tracker->track($url3);
```

 I'm waiting for your thoughts, and If you agree with these suggestions, I can work on it.

**Comment by peter279k** [comment]
It seems that you want to customize and extend/implement the Guzzle client then pass this client class object to the `Tracker class` rather than using the `Guzzle` client call directly inside the `Tracker` class.

To be compatible with current version, it should be great for having the optional parameter to pass the Tracker class.

Go for it and make the PR!

**Comment by AmraniCh** [comment]
Oops sorry for the assignment.

> rather than using the `Guzzle` client call directly inside the `Tracker` class

The Guzzle client will be used as the default HTTP client, but if a user passes another implementation of our HTTP client interface, then this client will be used instead of Guzzle.

> It seems that you want to customize and extend/implement the Guzzle client

We want to use the Guzzle client in our default implementation of the HTTP clients interface `Lee\Http\Client`.

**Comment by peter279k** [comment]
Thanks for your reply and explanation. It seems to be great. You can work on this PR after the #1 is merged :).

**Comment by AmraniCh** [comment]
Okey 👍 

You haven't mentioned anything about my suggestion to have the `Tracker` class stateless with URLs, Does that mean you agree with this?
> I suggest having the tracker class stateless, which means removing the `$url` property and let users work with only one instance to truck multiple URLs, like:

**Comment by peter279k** [comment]
> Okey 👍
> 
> You haven't mentioned anything about my suggestion to have the `Tracker` class stateless with URLs, Does that mean you agree with this?
> 
> > I suggest having the tracker class stateless, which means removing the `$url` property and let users work with only one instance to truck multiple URLs, like:

It seems that you want to let `Tracker` class be reusable and we can consider defining the `tracker` method and remove the `$url` variable in the `__constructor` parameter.

**Comment by AmraniCh** [comment]
I have done some research about the potential differences between the different HTTP clients available for PHP (Guzzle, Symfony HTTP client ..), and as a result In terms of performance, I arrived at the conclusion "there is no such considerable difference in terms of requests speed that pushes a user to prefer one library over another" at least for synchronous HTTP requests [see](https://github.com/Insolita/php-async-benchmarks).

In addition, the Guzzle HTTP client has what is called [Handlers](https://docs.guzzlephp.org/en/stable/handlers-and-middleware.html) for sending HTTP requests, the library has different handlers and the choice of that handler is done at runtime depending on the system extensions available (cURL basically).

For all these mentions above, I see to stick with Guzzle client internally and just lets users to choose some useful request configuration that they might need (eg. request timeout, proxy ...) and passing the configuration as an array into the trucker object constructor.

```php
$tracker = new Tracker([
  'proxy' => 'http://username:password@192.168.16.1:10',
  'timeout' => 1,
]);
$results = $tracker->track($url);
```

Of course, these request options must be supported by our internal HTTP client library (In the case of Guzzle see [Guzzle request options](https://docs.guzzlephp.org/en/stable/request-options.html)), but we have to be careful with these options and provide minimal options as much as possible because if we switch the library for some reason later these options must be still supported.

**Comment by AmraniCh** [comment]
> It seems that you want to let `Tracker` class be reusable and we can consider defining the `tracker` method and remove the `$url` variable in the `__constructor` parameter.

Yes exactly, the `$url` parameter will be no longer as a state property of the Trucker class, which means also removing the static method `Trucker::trackFromUrl` and switch the `Trucker::validateUrl` from static method into an instance method.

**Comment by peter279k** [comment]
Thanks for your reply and clear explanation. Please create the PR and let us review changed codes.

> Yes exactly, the `$url` parameter will be no longer as a state property of the Trucker class, which means also removing the static method `Trucker::trackFromUrl` and switch the `Trucker::validateUrl` from static method into an instance method.

To be compatible with the `Tracker::trackFromUrl` method for devleopers to track the URL at one time, I think we should keep the method callable. And implement the `track` method to do as you want to.

**Comment by AmraniCh** [comment]
> To be compatible with the `Tracker::trackFromUrl` method for devleopers to track the URL at one time, I think we should keep the method callable. And implement the `track` method to do as you want to.

Hmm, okay it sounds good, I'll create the PR soon.

**Comment by AmraniCh** [comment]
Emm, this issue should be still open?
